export const HandJoint = Object.freeze({
    WRIST: 0,

    THUMB_METACARPAL: 1,
    THUMB_PHALANX_PROXIMAL: 2,
    THUMB_PHALANX_DISTAL: 3,
    THUMB_TIP: 4,

    INDEX_METACARPAL: 5,
    INDEX_PHALANX_PROXIMAL: 6,
    INDEX_PHALANX_INTERMEDIATE: 7,
    INDEX_PHALANX_DISTAL: 8,
    INDEX_TIP: 9,

    MIDDLE_METACARPAL: 10,
    MIDDLE_PHALANX_PROXIMAL: 11,
    MIDDLE_PHALANX_INTERMEDIATE: 12,
    MIDDLE_PHALANX_DISTAL: 13,
    MIDDLE_TIP: 14,

    RING_METACARPAL: 15,
    RING_PHALANX_PROXIMAL: 16,
    RING_PHALANX_INTERMEDIATE: 17,
    RING_PHALANX_DISTAL: 18,
    RING_TIP: 19,

    PINKY_METACARPAL: 20,
    PINKY_PHALANX_PROXIMAL: 21,
    PINKY_PHALANX_INTERMEDIATE: 22,
    PINKY_PHALANX_DISTAL: 23,
    PINKY_TIP: 24,
});
export type HandJoint = typeof HandJoint[keyof typeof HandJoint];


// Note: thumb has no "intermediate" phalanx joint so its array is shorter than the rest.
export const Fingers = Object.freeze({
    THUMB: [HandJoint.THUMB_PHALANX_PROXIMAL, HandJoint.THUMB_PHALANX_DISTAL, HandJoint.THUMB_TIP],
    INDEX: [HandJoint.INDEX_PHALANX_PROXIMAL, HandJoint.INDEX_PHALANX_INTERMEDIATE, HandJoint.INDEX_PHALANX_DISTAL, HandJoint.INDEX_TIP],
    MIDDLE: [HandJoint.MIDDLE_PHALANX_PROXIMAL, HandJoint.MIDDLE_PHALANX_INTERMEDIATE, HandJoint.MIDDLE_PHALANX_DISTAL, HandJoint.MIDDLE_TIP],
    RING: [HandJoint.RING_PHALANX_PROXIMAL, HandJoint.RING_PHALANX_INTERMEDIATE, HandJoint.RING_PHALANX_DISTAL, HandJoint.RING_TIP],
    PINKY: [HandJoint.PINKY_PHALANX_PROXIMAL, HandJoint.PINKY_PHALANX_INTERMEDIATE, HandJoint.PINKY_PHALANX_DISTAL, HandJoint.PINKY_TIP],
});
export type Fingers = typeof Fingers[keyof typeof Fingers];
